import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import { StorageService } from '@/lib/storage/service';
import type { Prisma } from '@/app/generated/prisma';

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '1pt solid #ccc',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    marginTop: 5,
  },
  section: {
    margin: 10,
    padding: 10,
  },
  row: {
    flexDirection: 'row',
    borderBottom: '1pt solid #eee',
    paddingVertical: 5,
  },
  col: {
    flex: 1,
    fontSize: 10,
  },
  colHeader: {
    flex: 1,
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: '#f0f0f0',
    padding: 5,
  },
  bold: {
    fontWeight: 'bold',
  }
});

type ServiceWithRelations = Prisma.ServiceGetPayload<{
  include: {
    client: true;
    shipments: true;
    routes: { include: { stops: true } };
  };
}>;

const LoadingOrderDocument = ({ service }: { service: ServiceWithRelations }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Loading Order: {service.serviceNumber}</Text>
        <Text style={styles.subtitle}>Date: {service.date.toLocaleDateString()}</Text>
        <Text style={styles.subtitle}>Client: {service.client.name} ({service.client.clientCode})</Text>
        {service.driverName && <Text style={styles.subtitle}>Driver: {service.driverName}</Text>}
        {service.vehiclePlate && <Text style={styles.subtitle}>Vehicle: {service.vehiclePlate}</Text>}
      </View>

      <View style={styles.section}>
        <Text style={{ fontSize: 16, marginBottom: 10, fontWeight: 'bold' }}>Shipments to Load</Text>

        <View style={{ flexDirection: 'row' }}>
          <Text style={styles.colHeader}>Tracking Number</Text>
          <Text style={styles.colHeader}>Type</Text>
          <Text style={styles.colHeader}>Weight (kg)</Text>
          <Text style={styles.colHeader}>Status</Text>
        </View>

        {service.shipments.map((shipment) => (
          <View key={shipment.id} style={styles.row}>
            <Text style={styles.col}>{shipment.trackingNumber}</Text>
            <Text style={styles.col}>{shipment.type}</Text>
            <Text style={styles.col}>{shipment.weight?.toString() || 'N/A'}</Text>
            <Text style={styles.col}>{shipment.status}</Text>
          </View>
        ))}
      </View>

      <View style={{ marginTop: 50, borderTop: '1pt solid #000', paddingTop: 10 }}>
        <Text style={{ fontSize: 10, textAlign: 'center' }}>
          Document generated by Transport ERP
        </Text>
      </View>
    </Page>
  </Document>
);

export class PdfService {
  /**
   * Generates a PDF loading order and uploads it to B2 Storage.
   */
  static async generateAndUploadLoadingOrder(service: ServiceWithRelations): Promise<{ url: string; path: string }> {
    try {
      const storage = StorageService.getInstance();

      // Generate PDF Buffer
      const buffer = await renderToBuffer(<LoadingOrderDocument service={service} />);

      // Define path in B2
      const path = `documents/loading-orders/${service.id}/${service.serviceNumber}.pdf`;

      // Upload to B2
      const uploadedFile = await storage.uploadFile(buffer, path, {
        contentType: 'application/pdf',
      });

      return {
        url: uploadedFile.url,
        path: uploadedFile.path,
      };
    } catch (error) {
      console.error('[PdfService] Error generating PDF:', error);
      throw new Error('Failed to generate loading order PDF');
    }
  }
}
