// components/features/loading-orders/LoadingOrdersTable.tsx
'use client';

import { useCallback, useMemo } from 'react';

import { useRouter, useSearchParams } from 'next/navigation';

import { FileCheck, Truck } from 'lucide-react';

import { Badge, Button, Card } from '@/components/ui';
import { DataTable, type Column } from '@/components/ui/DataTable';
import { formatDate } from '@/lib/utils/date-formats';
import type { LoadingOrderListItem, PaginatedLoadingOrders } from '@/types/loading-order';

interface LoadingOrdersTableProps {
  data: PaginatedLoadingOrders;
}

export function LoadingOrdersTable({ data }: Readonly<LoadingOrdersTableProps>) {
  const router = useRouter();
  const searchParams = useSearchParams();

  const handlePageChange = useCallback(
    (page: number) => {
      const params = new URLSearchParams(searchParams.toString());
      params.set('page', page.toString());
      router.push(`/documents/loading-orders?${params.toString()}`);
    },
    [searchParams, router]
  );

  const columns = useMemo(() => getColumns(), []);

  return (
    <Card className="overflow-hidden">
      <DataTable
        data={data.data}
        columns={columns}
        onRowClick={(order) => router.push(`/documents/loading-orders/${order.id}`)}
        pagination={{
          page: data.pagination.page,
          pageSize: data.pagination.limit,
          total: data.pagination.total,
          onPageChange: handlePageChange,
        }}
        striped
        stickyHeader
        emptyState={
          <div className="py-12">
            <FileCheck size={48} className="mx-auto mb-4 text-muted-foreground" />
            <h3 className="text-center text-lg font-medium">No loading orders yet</h3>
            <p className="text-center text-sm text-muted-foreground mt-1">
              Select services in the Services list and choose Create Loading Order
            </p>
            <div className="flex justify-center mt-4">
              <Button onClick={() => router.push('/services')} icon={<Truck size={16} />}>
                Go to Services
              </Button>
            </div>
          </div>
        }
      />
    </Card>
  );
}

export function LoadingOrdersTableSkeleton() {
  return <DataTable data={[]} columns={[]} loading loadingRows={5} />;
}

const getColumns = (): Column<LoadingOrderListItem>[] => [
  {
    key: 'orderNumber',
    header: 'Order #',
    width: '140px',
    accessor: (order) => (
      <span className="font-medium text-primary hover:underline">{order.orderNumber}</span>
    ),
  },
  {
    key: 'generatedAt',
    header: 'Generated',
    width: '160px',
    accessor: (order) => <span className="text-sm">{formatDate.dateTime(order.generatedAt)}</span>,
  },
  {
    key: 'generatedBy',
    header: 'Generated by',
    minWidth: '150px',
    accessor: (order) => <span className="text-sm">{order.generatedByName}</span>,
  },
  {
    key: 'services',
    header: 'Services',
    align: 'center',
    width: '100px',
    accessor: (order) => <span className="text-sm tabular-nums">{order.servicesCount}</span>,
  },
  {
    key: 'pdf',
    header: 'PDF',
    align: 'center',
    width: '130px',
    // Honest status (#32): "Available" appears only when a real stored file
    // exists (pdfPath is set by the #34 pipeline, never before).
    accessor: (order) =>
      order.hasPdf ? (
        <Badge variant="completed" size="sm">
          Available
        </Badge>
      ) : (
        <Badge size="sm">Not generated</Badge>
      ),
  },
];
